// Generated from `Qafilaa Site v2.dc.html` (handoff 13), lines 816-848.
// Transcribed 1:1 — every data-* hook is read by src/site/engine.ts,
// which has no compile-time link to this markup. Do not rename them.

export function SettingsAndSupport() {
  return (
    <section id="settings" data-sec="Settings &amp; support" data-tone="light" data-pad="1" style={{ position: 'relative', zIndex: '5', padding: '110px 56px 110px 132px' }}>
        <div data-plot="1" style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--sur)', marginBottom: '24px' }}>Waypoint 19 · Settings, privacy and help</div>
        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1fr) auto', gap: '52px', alignItems: 'start' }} data-cols="1">
          <div>
            <h2 data-lines="1" style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontWeight: '600', fontSize: 'clamp(30px,3.6vw,48px)', lineHeight: '1.1', letterSpacing: '-.02em', margin: '0', maxWidth: '18ch' }}>You can turn the safety net off. We would rather you didn't.</h2>
            <p data-rv="1" style={{ fontSize: '18px', lineHeight: '1.6', color: 'var(--mut)', maxWidth: '58ch', margin: '20px 0 0' }}>Every safety default is on, and every one of them is yours to change. Location sharing is scoped to the trip and ends when the trip does. Your data can be exported or deleted from inside the app, without emailing anyone.</p>
            <div data-toggles="1" style={{ marginTop: '28px', maxWidth: '620px', background: 'var(--card)', border: '1px solid var(--line)', borderRadius: '18px', overflow: 'hidden' }}></div>
            <div style={{ marginTop: '20px', maxWidth: '620px', background: 'var(--card)', border: '1px solid var(--line)', borderRadius: '18px', padding: '22px' }}>
              <div data-plot="1" style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--sur)' }}>U1 · Help centre</div>
              <h3 style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '20px', fontWeight: '500', margin: '10px 0 0' }}>Answers, then a human.</h3>
              <div style={{ marginTop: '14px', display: 'flex', flexDirection: 'column', gap: '2px' }}>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Is there an app to track a group of bikers on a ride?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Yes. Qafilaa shows every rider in the group on one live map for the whole trip, not just a one-off location share. You can see who is rolling, who is stopped and who is resting, how far the convoy is stretched from lead to sweep, and each rider's last known position and how fresh it is.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Does Qafilaa work where there is no mobile signal?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Yes. Every screen reads from the phone's own storage first. You download the route corridor as an offline map before you leave, and navigation steps down gracefully: live route, then cached route, then stored geometry, then a straight-line bearing to the next rally point. Anything you do offline is queued and syncs when a signal returns.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Does the app detect motorcycle crashes automatically?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Yes. Crash detection reads the phone's motion sensors and is on by default. When a hard impact is detected a countdown starts so you can cancel if you are fine. If it completes, an alert goes to the riders closest to you first with your position, your bearing and your blood group, and it queues and fires the moment any rider in the convoy gets a signal.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Can I plan the Manali–Leh–Manali circuit with fuel and rest stops?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Yes. You build the trip day by day with legs, distances, altitudes and passes, mark rest days, and pin rally points where the group regroups if comms drop. Stays are scoped to nights rather than days, so one base kept for three nights is a single booking. Inner Line permits are tracked per rider.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>How do riders split trip expenses?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Log any shared cost against the trip, choose who paid and how it splits, and Qafilaa keeps a running balance for every rider. Settle-up clears all debts in the fewest transfers. Amounts are held as integer paise so a split never loses money to rounding, and expenses logged offline reconcile later.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Does Qafilaa work outside India?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Yes. It is built for rides across India, Nepal and Bhutan. Trip money supports Indian Rupee, Nepalese Rupee, Bhutanese Ngultrum and US Dollar, with foreign spends auto-converting to your home currency at the day's rate.</p></details>
                <details className="qf-rcpt" style={{ borderBottom: '1px solid var(--line)', padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>What is a rally point?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>A rally point is a place the group agrees on before setting off. If communications drop, everyone rides to the next rally point and waits there. It needs no phone signal to work, which is why it is the fallback the whole app is built around.</p></details>
                <details className="qf-rcpt" style={{ padding: '11px 0' }}><summary style={{ cursor: 'pointer', fontSize: '15px', fontWeight: '500', minHeight: '24px' }}>Does live tracking drain the battery?</summary><p style={{ margin: '8px 0 0', fontSize: '14px', lineHeight: '1.55', color: 'var(--mut)' }}>Battery mode reduces how often your position is published on long straight legs and restores full frequency near passes and rally points, where knowing exactly where the group is matters most.</p></details>
              </div>
              <div style={{ display: 'flex', gap: '10px', marginTop: '16px', flexWrap: 'wrap' }}>
                <a href="/support" data-btn="1" style={{ display: 'flex', alignItems: 'center', minHeight: '44px', padding: '0 16px', border: '1px solid var(--line)', borderRadius: '12px', fontSize: '14px', color: 'var(--ink)' }}>Help centre</a>
                <a href="mailto:admin@qafilaa.in" data-btn="1" style={{ display: 'flex', alignItems: 'center', minHeight: '44px', padding: '0 16px', border: '1px solid var(--line)', borderRadius: '12px', fontSize: '14px', color: 'var(--ink)' }}>Contact us</a>
              </div>
              <p style={{ margin: '12px 0 0', fontSize: '14px', color: 'var(--mut)' }}>Every query gets a ticket and a timeline you can follow inside the app.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '18px', alignItems: 'flex-start' }} data-strip="1">
            <div data-dock="1" data-screen="settings" data-scale="0.54" data-kind="push" data-flowname="Settings and support" data-flow="settings,alerts,account,help,faqs,queries"></div>
            <div data-static="privacyT7" data-scale="0.54" style={{ marginTop: '40px' }}></div>
          </div>
        </div>
      </section>
  );
}
