# -*- coding: utf-8 -*-
"""Generate the open-source acknowledgements page from the app's real manifests.

Reads the Flutter app's pubspec.yaml (direct dependencies) and pubspec.lock
(resolved versions, full tree size), plus this site's package.json. Nothing is
typed by hand, so nothing can be mistyped.

Licence *texts* are deliberately not asserted here: pub.dev is authoritative and
each package's licence is one click away. Claiming a licence we have not read
would be worse than linking the source that has it.
"""
import os as _os
# Resolve everything from the repo root so this works on a fresh clone and in CI.
REPO = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
TOOLS = _os.path.join(REPO, 'tools')
import io
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

# The Flutter app is a sibling repo. Point QAFILAA_APP_DIR at it, or leave it
# beside this one. This generator is not run in CI for that reason.
APP = _os.environ.get('QAFILAA_APP_DIR') or _os.path.join(_os.path.dirname(REPO), 'Qafilaa react nativ app')
SITE = REPO
OUT = os.path.join(SITE, 'src', 'site', 'legal', 'LicensesBody.tsx')

# ── read the app's manifests ────────────────────────────────────────────────
y = io.open(os.path.join(APP, 'pubspec.yaml'), encoding='utf-8').read()
direct, section = [], None
for ln in y.split('\n'):
    if re.match(r'^[a-z_]+:', ln):
        section = ln.split(':')[0]
        continue
    if section == 'dependencies' and re.match(r'^  [a-z_0-9]+:', ln):
        direct.append(ln.strip().split(':')[0])

lock = io.open(os.path.join(APP, 'pubspec.lock'), encoding='utf-8').read()
entries = re.findall(r'\n  ([a-z_0-9]+):\n(.*?)(?=\n  [a-z_0-9]+:\n|\Z)', lock, re.S)
version = {}
for name, body in entries:
    m = re.search(r'version:\s*"?([^"\n]+)"?', body)
    if m:
        version[name] = m.group(1).strip()
total_packages = len(entries)

pkg = json.loads(io.open(os.path.join(SITE, 'package.json'), encoding='utf-8').read())

# ── grouping, by what the package is for ───────────────────────────────────
GROUPS = [
    ('State, routing and code generation',
     ['flutter_riverpod', 'riverpod_annotation', 'go_router', 'freezed_annotation', 'json_annotation']),
    ('Maps, location and geometry',
     ['google_maps_flutter', 'flutter_map', 'latlong2', 'geolocator']),
    ('Storage and the offline database',
     ['hive', 'hive_flutter', 'drift', 'sqlite3_flutter_libs', 'path_provider', 'path', 'flutter_secure_storage']),
    ('Networking and the live channel',
     ['dio', 'connectivity_plus', 'mqtt_client']),
    ('Firebase',
     ['firebase_core', 'firebase_messaging', 'firebase_crashlytics', 'firebase_analytics']),
    ('Sign-in',
     ['google_sign_in', 'sign_in_with_apple']),
    ('Sensors, permissions and staying awake',
     ['sensors_plus', 'permission_handler', 'flutter_foreground_task', 'wakelock_plus', 'package_info_plus']),
    ('Photos, documents and media',
     ['image_picker', 'image_picker_android', 'image_picker_platform_interface', 'cached_network_image',
      'crop_your_image', 'flutter_image_compress', 'flutter_svg', 'gal', 'pdfx', 'file_selector']),
    ('Notifications, speech and time',
     ['flutter_local_notifications', 'flutter_tts', 'flutter_timezone', 'timezone', 'intl']),
    ('Sharing, links and contacts',
     ['url_launcher', 'share_plus', 'flutter_contacts', 'collection']),
]

grouped = {n for _, names in GROUPS for n in names}
ungrouped = [d for d in direct if d not in grouped and d != 'flutter']
assert not ungrouped, 'dependency not assigned to a group: %s' % ungrouped


def rows_for(names):
    out = []
    for n in names:
        v = version.get(n)
        out.append("            ['%s', '%s'],"
                   % (n, ('version ' + v) if v else 'bundled with the Flutter SDK'))
    return '\n'.join(out)


site_deps = sorted(list(pkg['dependencies'].items()) + [('vite', pkg['devDependencies']['vite']),
                                                        ('typescript', pkg['devDependencies']['typescript'])])
site_rows = '\n'.join("            ['%s', '%s'],," % (k, v.lstrip('^~')) for k, v in site_deps).replace(',,', ',')

sections = []
for title, names in GROUPS:
    sections.append("""      <H2>%s</H2>
      <Rows
        rows={[
%s
        ]}
      />""" % (title, rows_for(names)))

body = '''// Open-source acknowledgements.
//
// GENERATED by scratchpad/genlicenses.py from the Flutter app's pubspec.yaml
// and pubspec.lock, plus this site's package.json — regenerate rather than
// editing, or it drifts from what actually ships.
//
// Licence texts are not reproduced. pub.dev is authoritative for every package
// below and each licence is one click from the package page; asserting a
// licence we have not read would be worse than linking the source that has it.
import { Callout, Doc, H2, Mail, P, Rows, UL } from './prose';

export function LicensesBody() {
  return (
    <Doc
      slug="qafilaa.in/licenses"
      deck="What Qafilaa is built on"
      title="Open source"
      lede="Qafilaa is assembled from work other people gave away. %d packages resolve into the app, %d of them chosen directly; this site adds a handful more. They are listed here because attribution is the price of that gift, and it is a low one."
      updated="20/08/2026"
    >
      <Callout label="In plain English">
        <UL>
          <li>Everything below is third-party open source, used under its own licence.</li>
          <li>Each package's licence and source are on its pub.dev or npm page, one click away.</li>
          <li>We do not reproduce the texts here rather than risk misquoting one.</li>
          <li>
            Want the complete resolved tree, all %d of them, with licences? Ask at <Mail subject="Open source" />{' '}
            and we will send it.
          </li>
        </UL>
      </Callout>

      <H2>The app</H2>
      <P>
        Built with <b>Flutter</b> and <b>Dart</b>, both from Google under a BSD-3-Clause licence. The packages
        below are the ones Qafilaa asks for by name; each pulls in its own dependencies, which is how %d direct
        choices become %d resolved packages.
      </P>

%s

      <H2>This website</H2>
      <P>
        Much smaller — the site is React and little else.
      </P>
      <Rows
        rows={[
%s
        ]}
      />
      <P>
        The two typefaces, <b>Hanken Grotesk</b> and <b>Space Grotesk</b>, are served by Google Fonts under the
        SIL Open Font License.
      </P>

      <H2>Corrections</H2>
      <P>
        If you maintain something on this page and the attribution is wrong, or missing, tell us at{' '}
        <Mail subject="Open source" /> and we will fix it. See also{' '}
        <a href="/subprocessors">Subprocessors</a>, which lists the services rather than the code.
      </P>
    </Doc>
  );
}
''' % (total_packages, len(direct) - 1, total_packages, len(direct) - 1, total_packages,
       '\n\n'.join(sections), site_rows)

io.open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
print('LicensesBody.tsx written: %d direct deps in %d groups, %d packages total'
      % (len(direct) - 1, len(GROUPS), total_packages))
