// Open-source acknowledgements.
//
// GENERATED by scratchpad/genlicenses.py from the Flutter app's pubspec.yaml
// and pubspec.lock, plus this site's package.json — regenerate rather than
// editing, or it drifts from what actually ships.
//
// Licence texts are not reproduced. pub.dev is authoritative for every package
// below and each licence is one click from the package page; asserting a
// licence we have not read would be worse than linking the source that has it.
import { Callout, Doc, H2, Mail, P, Rows, UL } from './prose';

export function LicensesBody() {
  return (
    <Doc
      slug="qafilaa.in/licenses"
      deck="What Qafilaa is built on"
      title="Open source"
      lede="Qafilaa is assembled from work other people gave away. 283 packages resolve into the app, 49 of them chosen directly; this site adds a handful more. They are listed here because attribution is the price of that gift, and it is a low one."
      updated="20/08/2026"
    >
      <Callout label="In plain English">
        <UL>
          <li>Everything below is third-party open source, used under its own licence.</li>
          <li>Each package's licence and source are on its pub.dev or npm page, one click away.</li>
          <li>We do not reproduce the texts here rather than risk misquoting one.</li>
          <li>
            Want the complete resolved tree, all 283 of them, with licences? Ask at <Mail subject="Open source" />{' '}
            and we will send it.
          </li>
        </UL>
      </Callout>

      <H2>The app</H2>
      <P>
        Built with <b>Flutter</b> and <b>Dart</b>, both from Google under a BSD-3-Clause licence. The packages
        below are the ones Qafilaa asks for by name; each pulls in its own dependencies, which is how 49 direct
        choices become 283 resolved packages.
      </P>

      <H2>State, routing and code generation</H2>
      <Rows
        rows={[
            ['flutter_riverpod', 'version 3.3.2'],
            ['riverpod_annotation', 'version 4.0.3'],
            ['go_router', 'version 17.3.0'],
            ['freezed_annotation', 'version 3.1.0'],
            ['json_annotation', 'version 4.12.0'],
        ]}
      />

      <H2>Maps, location and geometry</H2>
      <Rows
        rows={[
            ['google_maps_flutter', 'version 2.18.0'],
            ['flutter_map', 'version 8.3.1'],
            ['latlong2', 'version 0.9.1'],
            ['geolocator', 'version 14.0.3'],
        ]}
      />

      <H2>Storage and the offline database</H2>
      <Rows
        rows={[
            ['hive', 'version 2.2.3'],
            ['hive_flutter', 'version 1.1.0'],
            ['drift', 'version 2.34.3'],
            ['sqlite3_flutter_libs', 'version 0.6.0+eol'],
            ['path_provider', 'version 2.1.6'],
            ['path', 'version 1.9.1'],
            ['flutter_secure_storage', 'version 10.3.1'],
        ]}
      />

      <H2>Networking and the live channel</H2>
      <Rows
        rows={[
            ['dio', 'version 5.11.0'],
            ['connectivity_plus', 'version 7.3.1'],
            ['mqtt_client', 'version 10.11.11'],
        ]}
      />

      <H2>Firebase</H2>
      <Rows
        rows={[
            ['firebase_core', 'version 4.12.1'],
            ['firebase_messaging', 'version 16.4.3'],
            ['firebase_crashlytics', 'version 5.2.6'],
            ['firebase_analytics', 'version 12.4.5'],
        ]}
      />

      <H2>Sign-in</H2>
      <Rows
        rows={[
            ['google_sign_in', 'version 7.2.0'],
            ['sign_in_with_apple', 'version 8.1.0'],
        ]}
      />

      <H2>Sensors, permissions and staying awake</H2>
      <Rows
        rows={[
            ['sensors_plus', 'version 7.1.0'],
            ['permission_handler', 'version 12.0.3'],
            ['flutter_foreground_task', 'version 9.2.2'],
            ['wakelock_plus', 'version 1.7.0'],
            ['package_info_plus', 'version 10.2.1'],
        ]}
      />

      <H2>Photos, documents and media</H2>
      <Rows
        rows={[
            ['image_picker', 'version 1.2.3'],
            ['image_picker_android', 'version 0.8.13+19'],
            ['image_picker_platform_interface', 'version 2.11.1'],
            ['cached_network_image', 'version 3.4.1'],
            ['crop_your_image', 'version 2.0.0'],
            ['flutter_image_compress', 'version 2.5.1'],
            ['flutter_svg', 'version 2.3.0'],
            ['gal', 'version 2.3.3'],
            ['pdfx', 'version 2.9.2'],
            ['file_selector', 'version 1.1.0'],
        ]}
      />

      <H2>Notifications, speech and time</H2>
      <Rows
        rows={[
            ['flutter_local_notifications', 'version 22.2.0'],
            ['flutter_tts', 'version 4.2.5'],
            ['flutter_timezone', 'version 5.1.0'],
            ['timezone', 'version 0.11.1'],
            ['intl', 'version 0.20.3'],
        ]}
      />

      <H2>Sharing, links and contacts</H2>
      <Rows
        rows={[
            ['url_launcher', 'version 6.3.2'],
            ['share_plus', 'version 13.3.0'],
            ['flutter_contacts', 'version 2.3.1'],
            ['collection', 'version 1.19.1'],
        ]}
      />

      <H2>This website</H2>
      <P>
        Much smaller. The site is React and little else.
      </P>
      <Rows
        rows={[
            ['react', '18.3.1'],
            ['react-dom', '18.3.1'],
            ['typescript', '5.6.3'],
            ['vite', '5.4.10'],
        ]}
      />
      <P>
        The two typefaces, <b>Hanken Grotesk</b> and <b>Space Grotesk</b>, are served by Google Fonts under the
        SIL Open Font License.
      </P>

      <H2>Corrections</H2>
      <P>
        If you maintain something on this page and the attribution is wrong, or missing, tell us at{' '}
        <Mail subject="Open source" /> and we will fix it. See also{' '}
        <a href="/subprocessors">Subprocessors</a>, which lists the services rather than the code.
      </P>
    </Doc>
  );
}
