// Generated from `Qafilaa Site v2.dc.html` (handoff 12), lines 1289-1327.
// Transcribed 1:1 — every data-* hook is read by src/site/engine.ts,
// which has no compile-time link to this markup. Do not rename them.

export function SupportBody() {
  return (
    <article>
            <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.16em', textTransform: 'uppercase', color: '#6E6B63' }}>qafilaa.in/support</div>
            <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '19px', fontWeight: '500', color: '#0A6068', marginTop: '22px' }}>Answers, then a human</div>
            <h1 style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontWeight: '600', fontSize: 'clamp(38px,5vw,58px)', lineHeight: '1.04', letterSpacing: '-.025em', margin: '10px 0 0' }}>Help centre</h1>
            <p style={{ margin: '20px 0 0', maxWidth: '64ch', fontSize: '19px', lineHeight: '1.6', color: '#4A4842', textWrap: 'pretty' }}>Every query gets a ticket and a timeline you can follow inside the app. Twelve answers are stored on your phone so they work in a dead zone, which is usually where you need them.</p>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: '18px', marginTop: '40px', maxWidth: '1000px' }}>
              <div style={{ background: '#FFFFFF', border: '1px solid #DCD6C9', borderRadius: '16px', padding: '24px' }}>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: '#6E6B63' }}>Email</div>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '19px', fontWeight: '500', marginTop: '9px' }}><a href="mailto:admin@qafilaa.in">admin@qafilaa.in</a></div>
                <p style={{ margin: '9px 0 0', fontSize: '15.5px', lineHeight: '1.6', color: '#4A4842' }}>Anything at all. We answer within two working days.</p>
              </div>
              <div style={{ background: '#FFFFFF', border: '1px solid #DCD6C9', borderRadius: '16px', padding: '24px' }}>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: '#6E6B63' }}>WhatsApp</div>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '19px', fontWeight: '500', marginTop: '9px' }}><a href="https://wa.me/918830997757" target="_blank" rel="noopener">+91 88309 97757</a></div>
                <p style={{ margin: '9px 0 0', fontSize: '15.5px', lineHeight: '1.6', color: '#4A4842' }}>Quickest for a question mid-trip.</p>
              </div>
              <div style={{ background: '#FFFFFF', border: '1px solid #DCD6C9', borderRadius: '16px', padding: '24px' }}>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '11px', letterSpacing: '.14em', textTransform: 'uppercase', color: '#B26B00' }}>In an emergency</div>
                <div style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontSize: '19px', fontWeight: '500', marginTop: '9px' }}>Call 112, not us</div>
                <p style={{ margin: '9px 0 0', fontSize: '15.5px', lineHeight: '1.6', color: '#4A4842' }}>Qafilaa alerts your crew. It does not contact emergency services.</p>
              </div>
            </div>

            <h2 style={{ fontFamily: '\'Space Grotesk\',sans-serif', fontWeight: '600', fontSize: '26px', letterSpacing: '-.015em', margin: '56px 0 0' }}>Frequently asked</h2>
            <div style={{ marginTop: '20px', maxWidth: '70ch', display: 'flex', flexDirection: 'column', gap: '2px' }}>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Is there an app to track a group of bikers on a ride?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Yes. Qafilaa shows every rider in the group on one live map for the whole trip, not just a one-off location share. You can see who is rolling, who is stopped and who is resting, how far the convoy is stretched from lead to sweep, and each rider's last known position and how fresh it is.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Does SOS work without internet?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>With no data, Qafilaa falls back to SMS — your emergency contacts get your last known pin, your blood group and allergies, and a link that opens once they are back in coverage. Tested down to 2G. The fallback is automatic. It still cannot reach anyone with no signal at all, and it does not call emergency services.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Does the app detect crashes automatically?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Yes, and it is on by default. Crash detection reads your phone's motion sensors on the device. When a hard impact is detected a countdown starts so you can cancel if you are fine. If it completes, an alert goes to the riders closest to you first with your position, your bearing and your blood group, and it queues and fires the moment any rider in the convoy gets a signal.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Does everyone in the group need the app?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>The leader and anyone you want on the live map need it. Riders without the app can still be added as a name and phone number, and they will receive rally-point details over SMS.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>How long is my live location shared?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Only while a ride is active, and only with riders in that convoy. It stops the moment the ride ends, you leave the group, or you flip Location off in Settings. Raw traces are deleted after 90 days, or 7 if you shorten the window.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>What happens if my phone dies mid-ride?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Your marker goes grey and the group sees "last seen 14 min ago" with your final pin, so they know exactly where to backtrack to.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Who can see my medical card?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Nobody, until an SOS or a crash alert fires. Then the responding riders and your emergency contacts see a summary — blood group, allergies, conditions.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Can I plan the Manali–Leh–Manali circuit with fuel and rest stops?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Yes. You build the trip day by day with legs, distances, altitudes and passes, mark rest days, and pin rally points where the group regroups if comms drop. Stays are scoped to nights rather than days, so one base kept for three nights is a single booking. Inner Line permits are tracked per rider.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>How do riders split trip expenses?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Log any shared cost against the trip, choose who paid and how it splits, and Qafilaa keeps a running balance for every rider. Settle-up clears all debts in the fewest transfers. Amounts are held as integer paise so a split never loses money to rounding, and expenses logged offline reconcile later.</p></details>
              <details className="qf-rcpt" style={{ borderBottom: '1px solid #DCD6C9', padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>Does live tracking drain the battery?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>Battery mode reduces how often your position is published on long straight legs and restores full frequency near passes and rally points, where knowing exactly where the group is matters most.</p></details>
              <details className="qf-rcpt" style={{ padding: '16px 0' }}><summary style={{ cursor: 'pointer', fontSize: '17px', fontWeight: '500', minHeight: '26px' }}>How do I delete my data or my account?</summary><p style={{ margin: '12px 0 0', fontSize: '16.5px', lineHeight: '1.65', color: '#4A4842' }}>From inside the app, or by email if you no longer have it. See <a href="/delete-data">Delete my data</a> and <a href="/delete-account">Delete your account</a>.</p></details>
            </div>
          </article>
  );
}
